# Call like: DRONE_ID=<id> tmuxp load drone

session_name: drone_${DRONE_ID}
environment:
  DRONE_ID: ${DRONE_ID}
  ROS_NAMESPACE: drone_${DRONE_ID}
  NUM_AGENTS: ${NUM_AGENTS}

windows:
  - zsh:
    focus: true
    panes:
      - #
  - window_name: loc
    panes:
      - wait_for_ros; roslaunch object_detection relative_localization_simulation_node.launch
  - window_name: ctrl
    panes:
      - wait_for_ros; roslaunch vswarm flocking.launch detections:=relative_localization_simulation_node/detections