# Call like: DRONE_ID=<id> tmuxp load drone

session_name: drone_${DRONE_ID}
environment:
  DRONE_ID: ${DRONE_ID}
  ROS_NAMESPACE: drone_${DRONE_ID}
  NUM_AGENTS: ${NUM_AGENTS}

windows:
  - zsh:
    focus: true
    panes:
      - #
  - window_name: tf
    panes:
      - wait_for_ros; roslaunch vswarm tf_cameras.launch
  - window_name: det
    panes:
      - wait_for_ros; roslaunch vswarm detection.launch
  - window_name: loc
    panes:
      - wait_for_ros; roslaunch vswarm localization.launch
  - window_name: track
    panes:
      - wait_for_ros; roslaunch vswarm tracking.launch
  - window_name: ctrl
    panes:
      - wait_for_ros; roslaunch vswarm flocking.launch