# Base
CBRK_IO_SAFETY: 22027       # Disable safety switch [true]
MAV_PROTO_VER: 2            # Always use MAVLink version 2

# Battery
BAT_A_PER_V: 65.0           # Battery amps per volt [A/V]
BAT_CAPACITY: 2250.0        # Battery capacity [mAh] -> Set to 90% of actual capacity
BAT_N_CELLS: 4              # Number of battery cells [#]
BAT_V_CHARGED: 4.2          # Full cell voltage (5C load) [V]
BAT_V_DIV: 11.0             # Battery voltage divider [V divider]
BAT_V_EMPTY: 3.4            # Empty cell voltage (5C load) [V]

# Camera trigger
TRIG_ACT_TIME: 1.0          # Camera trigger activation time [ms]
TRIG_INTERFACE: 1           # Camera trigger interface [GPIO]
TRIG_INTERVAL: 100.0        # Camera trigger interval [ms] -> 10Hz
TRIG_MODE: 1                # Camera trigger mode [Time based, on command]
TRIG_PINS: 56               # Camera trigger pin [5 and 6]
TRIG_POLARITY: 0            # Camera trigger polarity [Active low]

# Commander
COM_DISARM_LAND: 1.0        # Disarm timeout after land [s]

# TODO: these values depend on the RC config, dangerous to set here!)
# COM_FLTMODE1: 8             # Flight mode 1 [Stabilized]
# COM_FLTMODE4: 6             # Flight mode 6 [Position]
# COM_FLTMODE6: 11            # Flight mode 11 [Land]

# GPS
GPS_1_CONFIG: 104           # Serial configuration for main GPS [TELEM/SERIAL 4]
SER_TEL4_BAUD: 0            # Baudrate for TELEM/SERIAL 4 [Auto] -> GPS determines baud rate automatically

# Logging
SDLOG_UTC_OFFSET: 120       # UTC offset [min] -> UTC+1/CET (60min) for winter or UTC+2/CEST (120min) for summer time

# MAVLink
MAV_1_CONFIG: 102           # Serial configuration for MAVLink (instance 1) [TELEM 2]

# Multicopter position control
MPC_LAND_SPEED: 0.6         # Landing descend rate [m/s] (minimum value: 0.6)
MPC_THR_HOVER: 0.35         # Hover thrust [50%] -> Thrust stick center should hover

# PWM outputs
PWM_RATE: 400               # PWM output frequency for main outputs [Hz] -> Set to 0 for OneShot125

# Telemetry (no longer using because one RC -> multiple drones)
# TEL_FRSKY_CONFIG: 101       # Serial configuration for FrSky telemetry [TELEM 1]
