- x: 0.0
  y: 5.0
  z: 0
- x: 2.03
  y: 4.57
  z: 0
- x: 3.72
  y: 3.35
  z: 0
- x: 4.76
  y: 1.55
  z: 0
- x: 4.97
  y: -0.52
  z: 0
- x: 4.33
  y: -2.5
  z: 0
- x: 2.94
  y: -4.05
  z: 0
- x: 1.04
  y: -4.89
  z: 0
- x: -1.04
  y: -4.89
  z: 0
- x: -2.94
  y: -4.05
  z: 0
- x: -4.33
  y: -2.5
  z: 0
- x: -4.97
  y: -0.52
  z: 0
- x: -4.76
  y: 1.55
  z: 0
- x: -3.72
  y: 3.35
  z: 0
- x: -2.03
  y: 4.57
  z: 0
- x: -0.0
  y: 5.0
  z: 0
